update build hooks

diff --git a/hooks/post_push b/hooks/post_push
--- a/hooks/post_push
+++ b/hooks/post_push
@@ -4,6 +4,8 @@
 
 # push_platforms <target_tag> <base_tag>
 push_platforms () {
+	[ -n "${RATE_LIMITED+set}" ] && return
+
 	[ -n "${platforms:-}" ] || { echo "No platforms to push."; return 0; }
 
 	# remove duplicates
@@ -35,7 +37,25 @@ push_platforms () {
 	[ -n "${NOOP+set}" ] && echo '[NOOP]' && return 0
 	[ -n "${NO_PUSH+set}" ] && echo '[NO_PUSH]' && return 0
 #	{ "${manifest_cmd[@]}" | grep -i Digest | cut -d' ' -f2; } || { echo 'Could not push manifest.'; return 1; }
-	"${manifest_cmd[@]}" || { echo 'Could not push manifest.'; return 1; }
+#	"${manifest_cmd[@]}" || { echo 'Could not push manifest.'; return 1; }
+	local error
+	error="$("${manifest_cmd[@]}" 2>&1)";
+
+	if [ -n "${error}" ]; then
+		case ${error} in
+			*toomanyrequests*)
+				printf 'rate limited!\n\nSkipping remaining post_push..\n'
+				RATE_LIMITED='true'
+				POST_PUSH_SKIPPED="${DOCKER_TAG}"
+				return
+				;;
+			*)
+				printf 'unknown error:\n%s\n' "${error}"
+				exit 1
+				;;
+		esac
+		return 1
+	fi
 	echo
 }
 
@@ -45,6 +65,11 @@ elif [ ! -z "${SKIP_BUILD+set}" ]; then
 	echo "Skipping."
 elif [ -n "${NO_MANIFEST+set}" ]; then
 	echo "NO_MANIFEST is set, skipping post_push."
+elif [ -n "${NO_POST_PUSH+set}" ]; then
+	echo "NO_POST_PUSH is set, skipping post_push."
+elif [ -n "${RATE_LIMITED+set}" ]; then
+	echo "skip in post_push"
+	POST_PUSH_SKIPPED="${POST_PUSH_SKIPPED} ${DOCKER_TAG}"
 else
 	manifest_tags=()
 
@@ -64,7 +89,6 @@ else
 		push_platforms
 	fi
 fi
-echo
 
 ##	call any post_push_end() from build.conf
 #
